[package]
name = "nvpair-rs"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[workspace]
members = [
    "libnvpair-sys",
    "libnvpair",
]

[dependencies]
libc = "0.2"
thiserror = "1.0"

libnvpair = { path = "libnvpair" }